CREATE TABLE IF NOT EXISTS `products` (
    `id` INT AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `type` INT NOT NULL,
    `price` INT NOT NULL,
    `image` VARCHAR(255) DEFAULT NULL,
    `createdAt` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `version` INT NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;